### ISSUE TITLE
Avoid Gutenberg comments

### ISSUE THREAD

**Issue by Mte90** [GoogleChromeLabs/wp-origination#4]
I saw the project and seems interesting, I was just wondering if instead of comments that need to be parsed is not better to use javascript variables.  
As today:

```
<!-- origination
{
    "callback": "rel_canonical",
    "duration": 0.0026450157165527344,
    "index": 242,
    "name": "wp_head",
    "priority": 10,
    "source": {
        "file": "/app/public/core-dev/src/wp-includes/link-template.php",
        "name": "wp-includes",
        "type": "core"
    }
}
-->
```

```
<script>
origination.push({
    "callback": "rel_canonical",
    "duration": 0.0026450157165527344,
    "index": 242,
    "name": "wp_head",
    "priority": 10,
    "source": {
        "file": "/app/public/core-dev/src/wp-includes/link-template.php",
        "name": "wp-includes",
        "type": "core"
    }
});
</script>
```

With the `origination` var initialized in the head as example. 
In this way is not required to parse the whole page and js can be executed quickly.
AS it is a different url with a custom parameter to have js with a var doesn't create performance issues.

**Comment by westonruter** [comment]
Good question, but no, that won't help. The point of the comments is to be able to surround markup in the page with where it is coming from. So for example, if there is a `script` in the page, there needs to be a way to walk up the DOM tree to find the “open” Gutenberg-style HTML comments to identify the source for where that `script` came from.

Also, the data structure needing to be generated is a tree, not a list, as hooks often trigger other hooks, so there will be nested sources for given markup.

**Comment by Mte90** [comment]
Well comments are helpful if used with browser devtools so it is still possible to print them to wrapper the section without json embedded (that in devtools are not very readable). And adding also the js code.

If the purpose of the tool is to be used just with comments without a js library maybe is better to print the data in a different way instead of json, so they will be more readable.

JSON is a representation of an array in php, so it is possible to encode them in json also as tree. 
After all they will be parsed and put in a big array multidimensional now from the js library instead of writing them directly as js variables. So we will remove just a step.

**Comment by westonruter** [comment]
I'm not sure I understand. The point of the HTML comments is to annotate markup on the page with the source of where it came from.

**Comment by Mte90** [comment]
What I am trying to say if it is annotate markup to be used with browser developer tools is more useful to not print it in JSON.

If instead is to add support for tools that can elaborate those data there are other ways that keep everything more clean. Like a HTML comment to wrap it and a js code with printed the josn. 
In this way the parsing of html is not required and it is less complex.

**Comment by westonruter** [comment]
Yeah, the HTML comments are just the transport mechanism. They are not the ideal user interface for viewing. Both of these problems could be solved by "HTML source maps". See thread: https://twitter.com/igrigorik/status/1249857435323396096
